import { DarkScreen } from "@/components/main/dark-screen";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/navbar/navbar";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Trend Boutique - Fashion That Make Sense",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  pageProps: any; 
}

export default function RootLayout({ children, pageProps }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={pageProps?.session}>
          <Navbar />
          <DarkScreen />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
